### ISSUE TITLE
2016 GCC Data Hackathon Hub

### ISSUE THREAD

**Issue by jennaj** [bxlab/galaxy-hackathon#31]
**2016 GCC Data Hackathon Hub**

**The 2nd annual Data Wrangling Hackathon (“Datathon”) starts on Saturday, June 25 and continues on Sunday, June 26.** The associated Coding Hackathon https://github.com/bxlab/galaxy_hackathon/issues/1 overlaps with these dates. The working rooms of both hacks will be in close proximity and the two Hackathons will share meals to encourage and facilitate collaboration.
https://gcc2016.iu.edu/hacks/index.php
https://gcc2016.iu.edu/hacks/hacks-data.php

**Goals** 

Datathon Focus
- [ ] _Training Data_ (includes tutorial, example) https://github.com/bxlab/galaxy_hackathon/issues/28 @jennaj @griffinp @kpoterlo @yvanlebras @BoughAida @ssander5 @devikaatgit @cschu @tnabtaf 
- [ ] _Enhancing Shared Data Libs_ https://github.com/bxlab/galaxy_hackathon/issues/30 @ssander5 @jennaj 
- [ ] _Data Libs: Implement Controlled Vocab/Metadata/Source and Document as a Guide_ https://github.com/bxlab/galaxy_hackathon/issues/42 @ssander5 @jennaj
- [ ] _Best Practise Workflows_ https://github.com/bxlab/galaxy_hackathon/issues/29 @MoHeydarian @firaan1 @cschu @frederikcoppens 
  - [ ] Associated Datasets/Training Data
  - [ ] Interactive Tours based on content
  - [ ] Rnaseq variant calling pipeline
  - [ ] Share with GTN/GOBLET
  - [ ] Epigenomics analysis

Code Hack Focus Collaboration
- [ ] _Migrate intact Data Libraries from one Galaxy to another_ https://github.com/bxlab/galaxy_hackathon/issues/40 @ssander5 @jennaj 
- [ ] _Data Collections use and improvements_ https://github.com/bxlab/galaxy_hackathon/issues/32 @yvanlebras @frederikcoppens
- [ ] _Workflow improvements_ #29 @bgruening @yvanlebras @kpoterlo @jennaj @firaan1 @MoHeydarian @ssander5 @kmurat @cschu 
  - [ ] _Submit workflows to ToolShed via the Galaxy workflow interface_ https://github.com/bxlab/galaxy_hackathon/issues/4
- [ ] _Interactive Tours_ (seeding ideas) @yvanlebras @jennaj @kpoterlo
- [ ] _Create a Galaxy tool for the Canu Assembler_ #46 @nathanweeks 
- [ ] _Workflow Export to Unix_ #44 @ssander5 @frederikcoppens 
- [ ] _Creation/Export of High Res Images_ @MoHeydarian @firaan1 
  - [ ] Trackster PDF exporter https://github.com/bxlab/galaxy_hackathon/issues/17
  - [ ] Plots
  - [ ] Workflows #45
- [ ] _Galaxy Flavors_ @jennaj @kpoterlo @yvanlebras
- [ ]  _Usability Enhancements_ @firaan1 @jennaj 
  - [ ] accessing galaxy from command line api (sort of)
  - [ ] handling dataset names in workflow and deleting intermediate datasets after workflow completion
  - [ ] ggploting tools
  - [ ] Multiple history panel functionalities #33 

**Those participating in the GCC 2016 Datathon will have the opportunity to contribute to Galaxy in the following areas:**
1. Help to improve the overall Galaxy experience from a scientific usage perspective by suggesting how specific use-cases and other interface changes make “Using Galaxy” even better. 
2. Contribute ideas, provide example data, and perform follow-up testing for point-changes involving wrapped tools and/or the user interface for modifications performed in collaboration with the Coding Hackathon. Participants are encouraged to directly contribute to coding activities if interested. 
3. Develop best-practice workflows for publication at http://usegalaxy.org (tutorial design:  written, video, shared objects, tours - all could be part of this effort). There are many analysis areas that are well represented, yet there are opportunities for those in the scientific community to contribute and to share in their area of expertise.
4. Design representative testing/tutorial/training data to be published as _Shared Data Libraries_. Data that has been manipulated to be small, representative, and provides interesting results or highlights typical issues in the analysis, for a range of analysis workflows, is the primary goal. Which analysis to target? This is up to the participants. "Data" may include genomes, transcriptomes/exomes, NGS samples, reference annotation, and any other content required to execute complete workflows. 
5. General documentation of all flavors and types. Learned something new? Have a tip? We’ll wrangle these up during the Datathon and find the best place to get the information out there where other users can benefit.

**Aside from the aforementioned areas, all forms of contribution are welcome!**  Everyone is strongly encouraged to post suggestion/opinion/criticism below.

**We will be using Github to organize this year (not Trello). This is how it works:**
1. Get a Github account
2. Watch this repository and star this ticket
3. Share your ideas and feedback
4. New tickets opened and linked to this one - for concrete and actionable tasks directly related to Galaxy and/or specific Tools (created in the appropriate repositories).

See all soon! Cheers from Christian (@cschu), Frederik (@frederikcoppens), and Jennifer (@jennaj)

For prior comments, please see: https://github.com/galaxyproject/galaxy/issues/2520
